
rule all:
    input:
        "multiqc_report.html"

rule fastp:
    input:
        r1 = "raw_data/{sample}_R1.fastq",
        r2 = "raw_data/{sample}_R2.fastq"
    output:
        r1 = "fastp/{sample}_trimmed_R1.fastq.gz",
        r2 = "fastp/{sample}_trimmed_R2.fastq.gz",
        json = "fastp/{sample}.json",
        html = "fastp/{sample}.html"
    conda:
        "fastp"
    shell:
        """
        fastp \
        -i {input.r1} -I {input.r2} \
        -o {output.r1} -O {output.r2} \
        -j {output.json} -h {output.html}
        """

rule bowtie2:
    input:
        r1 = "fastp/{sample}_trimmed_R1.fastq.gz",
        r2 = "fastp/{sample}_trimmed_R2.fastq.gz"
    output:
        bam = "bowtie2/{sample}.bam"
    conda:
        "bowtie2"
    threads: 16
    params:
        ref = "~/references/AF266287"
    shell:
        """
        bowtie2 -x {params.ref} -1 {input.r1} -2 {input.r2} \
        --threads {threads} --sensitive-local |
        samtools sort - > {output.bam}
        """
rule samtools_rmdup:
    input:
        bam = "bowtie2/{sample}.bam"
    output:
        bam = "samtools_rmdup/{sample}_rmdup.bam"
    conda:
        "samtools"
    shell:
        """
        samtools rmdup {input.bam} {output.bam}
        """

rule multiqc:
    input: 
        expand("fastp/{sample}.json",sample=['AF266287_sample1']),
        expand("samtools_rmdup/{sample}_rmdup.bam",sample=['AF266287_sample1'])
        # expand("picard/{sample}_duplicates_removed.bam",sample=['AF266287_sample']),
        # expand("picard/{sample}_picard.metrics",sample=['AF266287_sample'])
    output:
        "multiqc_report.html"
    conda:
        "multiqc"
    params: 
        config = "~/repositories/bioinformatics_pipelines/ref_assembly/config/multiqc.yaml"
    shell:
        """
        multiqc --config {params.config} -f .
        """
